### ISSUE TITLE
CDN for the released version

### ISSUE THREAD

**Issue by piotr-gawron** [maykinmedia/dual-listbox#15]
Do you plan to release it at CDN?

**Comment by MartinKolarik** [comment]
You can use https://www.jsdelivr.com/package/npm/dual-listbox

**Comment by JostCrow** [comment]
Now the CDN is available in the readme.

**Comment by piotr-gawron** [comment]
@JostCrow 
Are you sure that providing url to CDN with version pinned should be 1.0.8?

This release is actually broken...

I would change it into 1.0.7, or 1.0.9 when released.

**Comment by JostCrow** [comment]
Good point. I will change it
