### ISSUE TITLE
about versioning

### ISSUE THREAD

**Issue by piotr-gawron** [maykinmedia/dual-listbox#22]
I have a question regarding versioning.
I'm used to standard:
MAJOR.MINOR.PATCH

Which can be summarized more or less:
* patch is used for bugs only,
* minor used for new functionlities, etc.
* major for not backward compatible changes

What are you using?

**Comment by piotr-gawron** [comment]
Ok I found the info. You are using semver,
So my question is why are you changing only patch part?

**Comment by JostCrow** [comment]
You are correct. We should change the minor flag. not the patch flag.

**Comment by piotr-gawron** [comment]
Ok. Thanks for info
