### ISSUE TITLE
order of elements

### ISSUE THREAD

**Issue by piotr-gawron** [maykinmedia/dual-listbox#24]
I think it would be useful to allow user to change the order of elements on the list - sometimes order matter.

**Comment by JostCrow** [comment]
We could do this using data-order="1" and passing an ordered option. What are your ideas?

**Comment by shaikhspear16** [comment]
can we have an interface for it ?
Like ordering the selected items with arrow up or arrow down.

**Comment by JostCrow** [comment]
That would indeed be a good change. I will need to see when this can be build. Not that much free time at the moment. A pull request is always welcome.

**Comment by phorman** [comment]
For those that are dynamically populating the listbox, this can be done already, by linking your sort form elements to your data retrieval method. Do your sorting in the database query, and pass back the results.

**Comment by ssada1975** [comment]
In order to have sort working properly, when creating a new dual-list the option "showSortButtons: true" should be set. 
Then js code should be modified as follow

_onSortButtonClick(t, e) {
                t.preventDefault();
                let list = this.dualListbox.querySelector(".dual-listbox__selected");
                let orderedLIs = [...list.children].sort((a, b) =>
                    a.textContent.localeCompare(b.textContent)
                );
                if (e=="down") orderedLIs = orderedLIs.reverse();
                list.innerHTML = orderedLIs.map(li => li.outerHTML).join('');
            }
