### ISSUE TITLE
Disable or remove a button?

### ISSUE THREAD

**Issue by fdesvallees** [maykinmedia/dual-listbox#28]
Hello, this works very well. Is it possible to disable the "add all" button, or remove it completely?
thanks
François

**Comment by phorman** [comment]
Quick fix: To remove a button, all you need to do is set the button's css property to display:none.
Example using jQuery:
`$('.dual-listbox__button:nth-child(2)').hide()`

CSS Style Sheet:
`<style>
  .dual-listbox__button: nth-child(2) {
    display:none;
  } 
</style>
`

**Comment by renwarkurd** [comment]
dualListbox.add_all_button.remove()
