### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by roddajohn** [maykinmedia/dual-listbox#36]
`Uncaught ReferenceError: global is not defined` error is throw upon including through the CDN:

`<script src="https://cdn.jsdelivr.net/npm/dual-listbox/dist/dual-listbox.min.js"></script>`

**Comment by JostCrow** [comment]
I am working on a new version where this issue will be fixed.

**Comment by anitagraham** [comment]
Any progress?  Any workarounds?

**Comment by svenvandescheur** [comment]
@JostCrow can you have a look at this again?
