### ISSUE TITLE
Is Drag and Drop option avaiable

### ISSUE THREAD

**Issue by tahirhussains** [maykinmedia/dual-listbox#73]
How we can add draggable feature from one list to another list in this control.

**Comment by JostCrow** [comment]
Not yet. But a pull request with drag and drop support is just added.

**Comment by tahirhussains** [comment]
Can we drag and drop on the same right list box?
Looks like only left to right and right to left drag are enabled.
I want to drag and drop on the same list.

Thanks
tahir

**Comment by tahirhussains** [comment]
Thanks for the reply.
Yeah we need to sort as per user selected order to show the same in Grid
column order.

Thanks
Tahir
