### ISSUE TITLE
dist/dual-listbox.js doesn't correspond to the source file

### ISSUE THREAD

**Issue by piotr-gawron** [maykinmedia/dual-listbox#9]
Current (1.0.6) `dist/dual-listbox.js` is not up to date with the source code. It's reffering to version 1.0.3 of the source code.

**Comment by JostCrow** [comment]
I will take a look at what is wrong

**Comment by svenvandescheur** [comment]
did we forgot to run `gulp build`? 😨

**Comment by JostCrow** [comment]
I think so

**Comment by JostCrow** [comment]
@piotr-gawron  Version 1.0.7 is now published. Can you confirm that the right version is published?

**Comment by piotr-gawron** [comment]
@JostCrow Yes, everything is fine now. Thanks a lot.
