### ISSUE TITLE
Use without npm

### ISSUE THREAD

**Issue by mzhadigerov** [maykinmedia/dual-listbox#92]
Hi! Thanks for this repo. I'm new in front-end. How to use this without npm?
Using cdn, for example

**Comment by ducvu91** [comment]
OMG, you not read guide ?

**Comment by mzhadigerov** [comment]
@dickvu91 I don't remember why I left this comment, but I was able to fetch it using cdn. Maybe I didn't notice at first and went straight to the "issues". Anyways, this is resolved. Will close, thanks
